export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";

export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";

export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export default {
  FETCH_POST_FAILURE,
  FETCH_POST_SUCCESS,
  FETCH_POST_REQUEST,
  FETCH_USER_FAILURE,
  FETCH_USER_SUCCESS,
  FETCH_USER_REQUEST,
};
